[tool.poetry]
name = "srnn"
version = "0.1.0"
description = ""
authors = ["Raphael Nepomuceno <58113327+rphln@users.noreply.github.com>"]
license = "MIT"

[tool.isort]
profile = "black"

[tool.poetry.dependencies]
python = "^3.7"
tqdm = "*"
torch = "*"
torchvision = "*"
click = "*"
tensorboard = "*"
kornia = "*"
scikit-learn = "*"
h5py = "*"
matplotlib = "*"

[tool.poetry.dev-dependencies]
black = {version = "^20.8b1", allow-prereleases = true}
isort = "^5.8.0"
jupytext = "^1.11.1"
torch-tb-profiler = "^0.1.0"
ipykernel = "^5.5.3"
ipywidgets = "^7.6.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
